AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFront Distribution and S3 bucket for static site + API Gateway origin (no custom domain)

Parameters:
  BucketName:
    Type: String
    Description: Name for the S3 bucket to create for static hosting.
  ENV:
    Type: String
    Description: "The deployment environment (dev, stage, prod)."

Resources:
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${BucketName}-OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  EditLabsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  EditLabsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    Properties:
      Bucket: !Ref EditLabsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${EditLabsBucket}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: Static React App + API Gateway Routing (no custom domain)
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt EditLabsBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        CustomErrorResponses:
          - ErrorCode: 404
            ResponsePagePath: /index.html
            ResponseCode: 200
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponsePagePath: /index.html
            ResponseCode: 200
            ErrorCachingMinTTL: 300

  # SSM parameter for the bucket name
  ParameterGlideeBucketsEditlabs:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ENV}/s3/edit-labs"
      Type: String
      Value: !Ref BucketName
      Description: Editlabs bucket for EditLabs
      Tier: Standard

Outputs:
  EditLabsBucketName:
    Description: The name of the created S3 bucket
    Value: !Ref EditLabsBucket

  CloudFrontDomainName:
    Description: CloudFront distribution domain
    Value: !GetAtt CloudFrontDistribution.DomainName

  CloudFrontDistributionID:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution


