AWSTemplateFormatVersion: '2010-09-09'
Description: Data core resources for database and storage (no external SSM ACM/domain/cognito dependencies).
Transform: AWS::Serverless-2016-10-31

Parameters:
  ENV:
    Type: String
    Description: "The deployment environment (dev, stage, prod)."
  S3BucketName:
    Type: String
    Description: S3 bucket name edit-labs

Resources:
  # The SSM Parameters
  ParameterGlideeTablesEditlabs:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${ENV}/tables/edit-labs
      Type: String
      Value: edit-labs
      Description: editlabs table
      Tier: Standard

  # DynamoDB Tables
  EditLabsDDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: edit-labs
      AttributeDefinitions:
        - AttributeName: org_id
          AttributeType: S
        - AttributeName: project_id
          AttributeType: S
      KeySchema:
        - AttributeName: org_id
          KeyType: HASH
        - AttributeName: project_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # Nested CDN application (NO custom domain / NO ACM)
  EditLabsCDNApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: cdn-template.yaml
      Parameters:
        BucketName: !Ref S3BucketName
        ENV: !Ref ENV
        # NOTE: Removed CustomDomainName and ACMCertificateArn

  # -------------------------
  # Cognito: User Pool & App (created locally)
  # -------------------------
  EditLabsUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "editlabs-userpool-${ENV}"
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireUppercase: false
          RequireNumbers: false
          RequireSymbols: false

  EditLabsUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "editlabs-client-${ENV}"
      GenerateSecret: false
      UserPoolId: !Ref EditLabsUserPool
      AllowedOAuthFlowsUserPoolClient: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH

  IdentityAuthPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub "glidee-identity-pool-${ENV}"
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref EditLabsUserPoolClient
          ProviderName: !Sub "cognito-idp.${AWS::Region}.amazonaws.com/${EditLabsUserPool}"
          ServerSideTokenCheck: true

  # Role for authenticated users
  IdentityPoolRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "identity-editlabs-role-${ENV}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref IdentityAuthPool
              "ForAnyValue:StringLike":
                cognito-identity.amazonaws.com:amr: authenticated
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonCognitoPowerUser

  # S3 Upload permission for authenticated users
  IdentityPoolAuthRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "s3-upload-policy-${ENV}"
      Roles:
        - !Ref IdentityPoolRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowUploadsToS3
            Effect: Allow
            Action:
              - "s3:PutObject"
              - "s3:PutObjectAcl"
            Resource: !Sub "arn:aws:s3:::${S3BucketName}/*"

  # Attach IdentityPool ↔ Role mapping
  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityAuthPool
      Roles:
        authenticated: !GetAtt IdentityPoolRole.Arn

Outputs:
  EditLabsDDBTableName:
    Description: "EditLabs DynamoDB Table Name"
    Value: !Ref EditLabsDDBTable

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref EditLabsUserPool

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref EditLabsUserPoolClient

  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref IdentityAuthPool
